#cloud-config
timezone: ${TIMEZONE}
locale: ${LOCALE}

users:
  - name: ansible
    system: true
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ANSIBLE_SSH_PUBKEY}

runcmd:
  - apt-get update
  - apt-get install -y qemu-guest-agent
  - systemctl enable ssh
  - reboot